//! Report Agent — generates scientific narratives and Q&A from pipeline results.
//!
//! Features: narrative generation, key finding extraction, interactive Q&A,
//! chart suggestion, file tree analysis.

use super::types::*;

/// Generate a structured report from pipeline results.
pub fn generate_report(
    pipeline_name: &str,
    files: &[ReportFile],
    log_summary: &str,
    diagnostics: &[String],
) -> ReportData {
    let mut findings = Vec::new();
    let mut caveats = Vec::new();
    let mut suggested_next = Vec::new();
    let mut total_size: i64 = 0;

    for f in files {
        total_size += f.size_bytes;
    }

    // QC summary
    let qc_summary = serde_json::json!({
        "total_files": files.len(),
        "total_size_mb": format!("{:.1}", total_size as f64 / 1048576.0),
        "directories": files.iter().filter(|f| f.is_dir).count(),
        "file_types": extract_file_types(files),
    });

    // Generate key findings from log/diagnostics
    if !diagnostics.is_empty() {
        for diag in diagnostics {
            if diag.contains("OOM") || diag.contains("137") {
                findings.push(ReportFinding {
                    finding: format!("Memory issue detected: {diag}"),
                    significance: "high".into(),
                    evidence: "System reported OOM".into(),
                });
            }
        }
    }

    // Standard findings from the log
    if log_summary.contains("error") || log_summary.contains("Error") {
        caveats.push("Some steps reported errors — review diagnostics".into());
    }

    // Suggest next steps based on typical RNA-seq/variant analysis
    let lower_name = pipeline_name.to_lowercase();
    if lower_name.contains("rna") || lower_name.contains("rnaseq") {
        suggested_next.push("Run DESeq2 or edgeR for differential expression analysis".into());
        suggested_next.push("Perform GO/KEGG enrichment on differentially expressed genes".into());
        suggested_next.push("Validate key findings with qPCR or alternative method".into());
    } else if lower_name.contains("variant") || lower_name.contains("wgs") {
        suggested_next.push("Annotate variants with VEP or ANNOVAR".into());
        suggested_next.push("Filter variants by quality and population frequency".into());
        suggested_next.push("Validate candidate variants with Sanger sequencing".into());
    } else {
        suggested_next.push("Review output files for quality metrics".into());
        suggested_next.push("Compare results with known benchmarks".into());
    }

    // Chart suggestions
    let charts = suggest_charts(files, pipeline_name);

    // Build narrative
    let narrative_md = build_narrative(
        pipeline_name,
        &qc_summary,
        &findings,
        &caveats,
        &suggested_next,
    );

    ReportData {
        qc_summary,
        key_findings: findings,
        narrative_md,
        caveats,
        suggested_next,
        file_tree: files.to_vec(),
        charts,
    }
}

/// Build a markdown-formatted narrative.
fn build_narrative(
    pipeline_name: &str,
    qc_summary: &serde_json::Value,
    findings: &[ReportFinding],
    caveats: &[String],
    suggested_next: &[String],
) -> String {
    let mut md = format!("# Pipeline Report: {pipeline_name}\n\n");

    md.push_str("## Summary\n\n");
    md.push_str(&format!(
        "Pipeline completed with **{}** output files.\n\n",
        qc_summary["total_files"]
    ));
    md.push_str(&format!(
        "Total output size: **{}**.\n\n",
        qc_summary["total_size_mb"].as_str().unwrap_or("unknown")
    ));

    if !findings.is_empty() {
        md.push_str("## Key Findings\n\n");
        for f in findings {
            md.push_str(&format!(
                "- **{}** (significance: {}) — {}\n",
                f.finding, f.significance, f.evidence
            ));
        }
        md.push('\n');
    }

    if !caveats.is_empty() {
        md.push_str("## Caveats\n\n");
        for c in caveats {
            md.push_str(&format!("- ⚠️ {c}\n"));
        }
        md.push('\n');
    }

    if !suggested_next.is_empty() {
        md.push_str("## Suggested Next Steps\n\n");
        for s in suggested_next {
            md.push_str(&format!("- 💡 {s}\n"));
        }
        md.push('\n');
    }

    md.push_str("---\n");
    md.push_str("*Report generated by oxo-flow AI Companion v0.8*\n");

    md
}

/// Suggest charts based on output files.
fn suggest_charts(files: &[ReportFile], pipeline_name: &str) -> Vec<ChartConfig> {
    let mut charts = Vec::new();
    let lower = pipeline_name.to_lowercase();

    let has_counts = files
        .iter()
        .any(|f| f.name.contains(".counts") || f.name.contains("featurecounts"));
    let has_vcf = files
        .iter()
        .any(|f| f.name.contains(".vcf") || f.name.contains(".gvcf"));
    let has_bam = files.iter().any(|f| f.name.contains(".bam"));
    let has_qc = files
        .iter()
        .any(|f| f.name.contains("_fastqc") || f.name.contains("qc_"));

    if has_counts && lower.contains("rna") {
        charts.push(ChartConfig {
            chart_type: "volcano".into(),
            title: "Differential Expression Volcano Plot".into(),
            spec: serde_json::json!({
                "mark": "point",
                "encoding": {
                    "x": {"field": "log2FC", "type": "quantitative", "title": "Log2 Fold Change"},
                    "y": {"field": "negLog10P", "type": "quantitative", "title": "-Log10(p-value)"},
                    "color": {"field": "significant", "type": "nominal"}
                }
            }),
        });
    }

    if has_vcf {
        charts.push(ChartConfig {
            chart_type: "bar".into(),
            title: "Variant Type Distribution".into(),
            spec: serde_json::json!({
                "mark": "bar",
                "encoding": {
                    "x": {"field": "variant_type", "type": "nominal", "title": "Variant Type"},
                    "y": {"field": "count", "type": "quantitative", "title": "Count"}
                }
            }),
        });
    }

    if has_qc || has_bam {
        charts.push(ChartConfig {
            chart_type: "line".into(),
            title: "Coverage Distribution".into(),
            spec: serde_json::json!({
                "mark": "line",
                "encoding": {
                    "x": {"field": "depth", "type": "quantitative", "title": "Sequencing Depth"},
                    "y": {"field": "fraction", "type": "quantitative", "title": "Fraction of Genome"}
                }
            }),
        });
    }

    if lower.contains("chip") {
        charts.push(ChartConfig {
            chart_type: "heatmap".into(),
            title: "Peak Signal Heatmap".into(),
            spec: serde_json::json!({
                "mark": "rect",
                "encoding": {
                    "x": {"field": "peak_region", "type": "nominal", "title": "Peak Region"},
                    "y": {"field": "sample", "type": "nominal", "title": "Sample"},
                    "color": {"field": "signal", "type": "quantitative"}
                }
            }),
        });
    }

    charts
}

/// Extract unique file extensions from the file list.
fn extract_file_types(files: &[ReportFile]) -> Vec<String> {
    let mut types: Vec<String> = files
        .iter()
        .filter_map(|f| {
            std::path::Path::new(&f.name)
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.to_string())
        })
        .collect();
    types.sort();
    types.dedup();
    types
}

/// Answer a question about the report using context.
pub fn answer_question(report: &ReportData, question: &str) -> String {
    let lower = question.to_lowercase();

    if lower.contains("file") || lower.contains("output") || lower.contains("result") {
        let total = report.file_tree.len();
        let total_size: i64 = report.file_tree.iter().map(|f| f.size_bytes).sum();
        format!(
            "The pipeline produced {total} output files totaling {:.1} MB. \
             The most common file types are: {}.",
            total_size as f64 / 1048576.0,
            extract_file_types(&report.file_tree).join(", ")
        )
    } else if lower.contains("quality") || lower.contains("qc") || lower.contains("good") {
        if report.caveats.is_empty() {
            "All quality checks passed. No significant issues detected.".to_string()
        } else {
            format!(
                "Some quality caveats to note: {}",
                report.caveats.join("; ")
            )
        }
    } else if lower.contains("next") || lower.contains("step") || lower.contains("suggest") {
        format!("Suggested next steps: {}", report.suggested_next.join("; "))
    } else if lower.contains("caveat") || lower.contains("limit") || lower.contains("caution") {
        if report.caveats.is_empty() {
            "No specific caveats identified for this run.".to_string()
        } else {
            format!("Caveats: {}", report.caveats.join("; "))
        }
    } else if lower.contains("chart")
        || lower.contains("plot")
        || lower.contains("graph")
        || lower.contains("visualize")
    {
        let charts: Vec<String> = report.charts.iter().map(|c| c.title.clone()).collect();
        format!("Available visualizations: {}", charts.join(", "))
    } else {
        format!(
            "Based on the analysis report for this run: the pipeline completed with {} output files. \
             {}",
            report.file_tree.len(),
            if report.key_findings.is_empty() {
                "No unexpected findings reported.".to_string()
            } else {
                format!(
                    "Key findings include: {}",
                    report
                        .key_findings
                        .iter()
                        .map(|f| f.finding.clone())
                        .collect::<Vec<_>>()
                        .join("; ")
                )
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_files() -> Vec<ReportFile> {
        vec![
            ReportFile {
                path: "/data/results/sample1.bam".into(),
                name: "sample1.bam".into(),
                size_bytes: 2_000_000_000,
                is_dir: false,
            },
            ReportFile {
                path: "/data/results/sample1.counts.tsv".into(),
                name: "sample1.counts.tsv".into(),
                size_bytes: 500_000,
                is_dir: false,
            },
            ReportFile {
                path: "/data/results/qc".into(),
                name: "qc".into(),
                size_bytes: 100_000,
                is_dir: true,
            },
            ReportFile {
                path: "/data/results/sample1_fastqc.html".into(),
                name: "sample1_fastqc.html".into(),
                size_bytes: 1_000_000,
                is_dir: false,
            },
        ]
    }

    #[test]
    fn test_generate_report_basic() {
        let report = generate_report(
            "rnaseq-test",
            &sample_files(),
            "All steps completed successfully",
            &[],
        );
        assert!(report.narrative_md.contains("Pipeline Report"));
        assert!(!report.file_tree.is_empty());
        assert!(report.qc_summary["total_files"].as_u64().unwrap() >= 4);
    }

    #[test]
    fn test_generate_report_with_diagnostics() {
        let report = generate_report(
            "rnaseq-test",
            &sample_files(),
            "OOM error",
            &["OOM detected at step 2".into()],
        );
        assert!(!report.key_findings.is_empty());
        assert!(report.key_findings[0].finding.contains("OOM"));
    }

    #[test]
    fn test_answer_about_files() {
        let report = generate_report("test", &sample_files(), "", &[]);
        let answer = answer_question(&report, "What output files were generated?");
        assert!(answer.contains("output files"));
    }

    #[test]
    fn test_answer_about_quality() {
        let report = generate_report("test", &sample_files(), "", &[]);
        let answer = answer_question(&report, "How is the quality?");
        assert!(!answer.is_empty());
    }

    #[test]
    fn test_answer_about_charts() {
        let report = generate_report("rnaseq-test", &sample_files(), "", &[]);
        let answer = answer_question(&report, "What charts are available?");
        assert!(answer.contains("visualization") || answer.contains("chart"));
    }

    #[test]
    fn test_extract_file_types() {
        let types = extract_file_types(&sample_files());
        assert!(types.contains(&"bam".to_string()));
        assert!(types.contains(&"tsv".to_string()));
    }

    #[test]
    fn test_chart_suggestion_rnaseq() {
        let charts = suggest_charts(&sample_files(), "rnaseq-analysis");
        assert!(
            charts.iter().any(|c| c.chart_type == "volcano"),
            "RNA-seq should suggest volcano"
        );
    }
}
