//! Agent types — shared agent message protocol and status types.
//!
//! All agents communicate through the uniform AgentMessage protocol.
//! The orchestrator dispatches tasks to specialized agents, each returning
//! structured results with confidence, evidence, and unknowns.

use serde::{Deserialize, Serialize};

/// Uniform agent message protocol — all agents use this.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentMessage {
    /// Agent name (e.g., "DataAgent", "ToolExpert")
    pub agent: String,
    /// Message type (e.g., "task", "result", "error", "progress")
    pub msg_type: String,
    /// Confidence in the result (0.0 - 1.0)
    pub confidence: f64,
    /// The payload data
    pub data: serde_json::Value,
    /// Source of evidence (how the agent knows this)
    pub evidence: Vec<EvidenceSource>,
    /// What the agent doesn't know
    pub unknowns: Vec<String>,
    /// Suggestions for next steps
    pub suggestions: Vec<String>,
}

/// Source of evidence for a finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceSource {
    /// Type of evidence: "file_scan", "user_input", "pattern_match", "ai_inference", "knowledge_base"
    pub source_type: String,
    /// Description of the evidence
    pub description: String,
    /// Confidence in this evidence (0.0 - 1.0)
    pub confidence: f64,
}

/// Agent status update for SSE streaming.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentStatus {
    pub agent: String,
    pub status: String,
    pub progress: f64,
    pub message: String,
}

/// Data perception finding — 4-level degradation model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataFinding {
    pub field: String,
    pub value: serde_json::Value,
    pub confidence: f64,
    pub source: String, // "file_scan" | "user_description" | "naming_convention" | "intent_only"
    pub evidence: String,
}

/// Data perception level (0-3)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum DataPerceptionLevel {
    /// Level 3: Real file system access — 100% accurate
    FileSystemAccess = 3,
    /// Level 2: User provides metadata description
    UserDescription = 2,
    /// Level 1: File naming convention only
    FileNamingConvention = 1,
    /// Level 0: Pure knowledge, no data
    IntentOnly = 0,
}

impl DataPerceptionLevel {
    pub fn as_u8(&self) -> u8 {
        match self {
            Self::FileSystemAccess => 3,
            Self::UserDescription => 2,
            Self::FileNamingConvention => 1,
            Self::IntentOnly => 0,
        }
    }
}

/// Data perception report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataPerceptionReport {
    pub data_level: u8,
    pub findings: Vec<DataFinding>,
    pub warnings: Vec<String>,
    pub suggestions: Vec<String>,
}

/// Tool recommendation from the Tool Expert Agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolRecommendation {
    pub rule_name: String,
    pub tool: String,
    pub purpose: String,
    pub key_params: serde_json::Value,
    pub resource_hint: ResourceHint,
    pub alternatives: Vec<String>,
    pub confidence: f64,
}

/// Resource hint for a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceHint {
    pub threads: u32,
    pub memory_gb: u32,
    pub disk_gb: Option<u32>,
    pub wall_time: Option<String>,
}

/// Monitor alert generated by the Monitor Agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitorAlert {
    pub level: AlertLevel,
    pub rule_name: Option<String>,
    pub prediction: String,
    pub suggestion: String,
    pub auto_fixable: bool,
    pub needs_approval: bool,
    pub timestamp: String,
}

/// Alert severity levels.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AlertLevel {
    /// Info: step completed, progress update
    Info,
    /// Warn: memory >80%, disk >85%, step slow
    Warn,
    /// Alert: predicted OOM, known error pattern. Auto-pause + suggest
    Alert,
    /// Critical: actual OOM, disk full, crash. Diagnose + one-click retry
    Critical,
}

impl AlertLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Warn => "warn",
            Self::Alert => "alert",
            Self::Critical => "critical",
        }
    }
}

/// Monitor agent status response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitorStatus {
    pub overall: String,
    pub alerts: Vec<MonitorAlert>,
    pub resource_forecast: ResourceForecast,
    pub estimated_completion: Option<String>,
}

/// Resource forecast from the Monitor Agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceForecast {
    pub cpu_trend: String,
    pub memory_trend: String,
    pub disk_trend: String,
    pub oom_risk: f64,
    pub timeout_risk: f64,
}

/// Report generated by the Report Agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportData {
    pub qc_summary: serde_json::Value,
    pub key_findings: Vec<ReportFinding>,
    pub narrative_md: String,
    pub caveats: Vec<String>,
    pub suggested_next: Vec<String>,
    pub file_tree: Vec<ReportFile>,
    pub charts: Vec<ChartConfig>,
}

/// A single finding in a report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportFinding {
    pub finding: String,
    pub significance: String,
    pub evidence: String,
}

/// A file in the report file tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportFile {
    pub path: String,
    pub name: String,
    pub size_bytes: i64,
    pub is_dir: bool,
}

/// Chart configuration for Vega-Lite.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChartConfig {
    pub chart_type: String, // "volcano", "heatmap", "coverage", "pathway", "bar", "line"
    pub title: String,
    pub spec: serde_json::Value, // Vega-Lite spec
}

/// Search result from the Search Agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    pub query: String,
    pub results: Vec<SearchItem>,
    pub total: usize,
    pub score: f64,
}

/// A single search result item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchItem {
    pub title: String,
    pub url: String,
    pub snippet: String,
    pub relevance_score: f64,
    pub source: String,
}

/// Environment detection result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvironmentInfo {
    pub name: String,
    pub available: bool,
    pub version: Option<String>,
    pub path: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_agent_message_roundtrip() {
        let msg = AgentMessage {
            agent: "DataAgent".into(),
            msg_type: "result".into(),
            confidence: 0.95,
            data: serde_json::json!({"files": []}),
            evidence: vec![EvidenceSource {
                source_type: "file_scan".into(),
                description: "Scanned 3 files".into(),
                confidence: 1.0,
            }],
            unknowns: vec!["library_type".into()],
            suggestions: vec!["Use STAR".into()],
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(back.agent, "DataAgent");
        assert!((back.confidence - 0.95).abs() < 0.01);
    }

    #[test]
    fn test_data_perception_levels() {
        assert_eq!(DataPerceptionLevel::FileSystemAccess.as_u8(), 3);
        assert_eq!(DataPerceptionLevel::IntentOnly.as_u8(), 0);
    }

    #[test]
    fn test_alert_level_serde() {
        let json = serde_json::json!("alert");
        let level: AlertLevel = serde_json::from_value(json).unwrap();
        assert_eq!(level, AlertLevel::Alert);
        assert_eq!(level.as_str(), "alert");
    }
}
