//! Knowledge source metadata (`knowledge_meta.json`) — freshness tracking.
//!
//! The knowledge update pipeline regenerates the embedded JSONL data files
//! and writes `knowledge_meta.json` next to them, documenting each source's
//! record count and generation timestamp. This module parses that metadata
//! and exposes staleness, so the CLI and tool responses can tell users how
//! fresh the embedded knowledge is — and the release pipeline can block
//! shipping auto-updated sources that have gone stale.
//!
//! Documented schema (plain JSON — the canonical `sources` array form):
//!
//! ```json
//! {
//!   "sources": [
//!     {
//!       "name": "bioconda_tools",
//!       "description": "Bioconda CLI tool database",
//!       "data_file": "bioconda_tools.jsonl",
//!       "count": 6132,
//!       "generated_at": "2026-08-22T10:54:00Z",
//!       "auto": true
//!     }
//!   ]
//! }
//! ```
//!
//! Contract: `count` equals the number of records (non-empty lines) in
//! `data_file`; `generated_at` is an RFC 3339 UTC timestamp; `auto: true`
//! means the update pipeline regenerated the source, `false` marks
//! manually curated data. For robustness the parser also accepts a
//! `sources` object keyed by source name, or a bare object of sources
//! (both shapes the update pipeline may emit).

use serde::{Deserialize, Serialize};
use std::sync::LazyLock;

/// Auto-updated sources older than this many days are reported stale.
///
/// Matches the release-pipeline gate (ci.yml's sync-version job blocks a
/// dispatch release when any `auto: true` source exceeds this age), so what
/// `ai status` flags is exactly what the release refuses to ship.
pub const STALE_AFTER_DAYS: u64 = 60;

/// One embedded knowledge source described by `knowledge_meta.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KnowledgeSource {
    /// Stable identifier (status output, freshness lines, tool lookups).
    /// May be absent in the named-object forms — the map key fills it in.
    #[serde(default)]
    pub name: String,
    /// Human-readable one-liner describing the source.
    #[serde(default)]
    pub description: String,
    /// JSONL data file embedded in the crate; `count` must equal its
    /// number of records.
    pub data_file: String,
    /// Number of records in `data_file` at generation time.
    pub count: usize,
    /// RFC 3339 generation timestamp (UTC).
    pub generated_at: String,
    /// `true` = regenerated by the update pipeline; `false` = manually curated.
    pub auto: bool,
}

impl KnowledgeSource {
    /// Whole days between generation and `now` (0 for future timestamps).
    pub fn staleness_days(&self, now: chrono::DateTime<chrono::Utc>) -> Option<u64> {
        let generated = chrono::DateTime::parse_from_rfc3339(&self.generated_at).ok()?;
        Some(
            now.signed_duration_since(generated.with_timezone(&chrono::Utc))
                .num_days()
                .max(0) as u64,
        )
    }

    /// `true` when an auto-updated source is older than [`STALE_AFTER_DAYS`].
    pub fn is_stale(&self, now: chrono::DateTime<chrono::Utc>) -> bool {
        self.auto
            && self
                .staleness_days(now)
                .is_some_and(|days| days > STALE_AFTER_DAYS)
    }

    /// `YYYY-MM-DD` rendering of the generation timestamp.
    pub fn generated_date(&self) -> Option<String> {
        chrono::DateTime::parse_from_rfc3339(&self.generated_at)
            .ok()
            .map(|ts| ts.format("%Y-%m-%d").to_string())
    }
}

/// The full metadata document: the list of knowledge sources.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KnowledgeMeta {
    pub sources: Vec<KnowledgeSource>,
}

impl KnowledgeMeta {
    /// Parse from the JSON content of `knowledge_meta.json`.
    ///
    /// Accepts every shape the update pipeline may emit: a `sources` array
    /// of objects, a `sources` object keyed by source name, or a bare
    /// object of sources with no `sources` key (the pipeline's fallback).
    pub fn parse(json: &str) -> Result<Self, String> {
        let value: serde_json::Value =
            serde_json::from_str(json).map_err(|e| format!("invalid knowledge_meta.json: {e}"))?;
        let sources = normalize_sources(&value)?;
        Ok(KnowledgeMeta { sources })
    }

    /// Look up a source by name.
    pub fn source(&self, name: &str) -> Option<&KnowledgeSource> {
        self.sources.iter().find(|s| s.name == name)
    }
}

/// Normalize the three accepted document shapes into a source list.
fn normalize_sources(value: &serde_json::Value) -> Result<Vec<KnowledgeSource>, String> {
    let raw = value.get("sources");
    match raw {
        None => {
            // Bare object of sources: top-level values are source objects
            // keyed by name (non-object values are ignored, as the update
            // pipeline's own consumers do).
            let Some(map) = value.as_object() else {
                return Err("knowledge_meta.json must be an object".into());
            };
            map.iter()
                .filter(|(_, v)| v.is_object())
                .map(|(name, v)| source_from_value(name, v))
                .collect()
        }
        Some(raw) if raw.is_array() => raw
            .as_array()
            .expect("checked is_array")
            .iter()
            .enumerate()
            .map(|(i, v)| {
                let src = source_from_value(&format!("source#{i}"), v)?;
                if src.name.is_empty() {
                    Err(format!("knowledge_meta.json source #{i} is missing a name"))
                } else {
                    Ok(src)
                }
            })
            .collect(),
        Some(raw) if raw.is_object() => raw
            .as_object()
            .expect("checked is_object")
            .iter()
            .map(|(name, v)| source_from_value(name, v))
            .collect(),
        Some(_) => Err("knowledge_meta.json 'sources' must be an object or array".into()),
    }
}

/// Deserialize one source object, filling `name` from the map key when the
/// object itself does not carry one.
fn source_from_value(
    fallback_name: &str,
    value: &serde_json::Value,
) -> Result<KnowledgeSource, String> {
    let mut src: KnowledgeSource = serde_json::from_value(value.clone())
        .map_err(|e| format!("invalid knowledge source: {e}"))?;
    if src.name.is_empty() {
        src.name = fallback_name.to_string();
    }
    Ok(src)
}

/// The metadata embedded at build time — `None` when the build predates
/// `knowledge_meta.json` (the update pipeline emits it on its first run).
pub fn embedded_meta() -> Option<&'static KnowledgeMeta> {
    static EMBEDDED: LazyLock<Option<KnowledgeMeta>> = LazyLock::new(|| {
        #[cfg(knowledge_meta_embedded)]
        {
            KnowledgeMeta::parse(include_str!("knowledge_meta.json")).ok()
        }
        #[cfg(not(knowledge_meta_embedded))]
        {
            None
        }
    });
    EMBEDDED.as_ref()
}

/// Compact freshness note appended to tool responses, e.g.
/// `Data: bioconda_tools generated 2026-08-22 (1 day ago), 6132 records`.
pub fn freshness_line(source: &KnowledgeSource, now: chrono::DateTime<chrono::Utc>) -> String {
    let date = source
        .generated_date()
        .unwrap_or_else(|| source.generated_at.clone());
    match source.staleness_days(now) {
        Some(days) => format!(
            "Data: {} generated {} ({} day{} ago), {} records",
            source.name,
            date,
            days,
            if days == 1 { "" } else { "s" },
            source.count
        ),
        None => format!(
            "Data: {} generated {} (date unparsable), {} records",
            source.name, date, source.count
        ),
    }
}

/// Freshness note for a source looked up by name (used by tool handlers).
pub fn freshness_line_for(
    meta: &KnowledgeMeta,
    name: &str,
    now: chrono::DateTime<chrono::Utc>,
) -> Option<String> {
    meta.source(name).map(|s| freshness_line(s, now))
}

/// Human-readable freshness row for `ai status`, e.g.
/// `bioconda_tools (auto) 6132 records, generated 2026-08-22 (1 day ago)`.
pub fn format_source_row(source: &KnowledgeSource, now: chrono::DateTime<chrono::Utc>) -> String {
    let mode = if source.auto { "auto" } else { "manual" };
    let date = source
        .generated_date()
        .unwrap_or_else(|| source.generated_at.clone());
    match source.staleness_days(now) {
        Some(days) => format!(
            "{} ({}) {} records, generated {} ({} day{})",
            source.name,
            mode,
            source.count,
            date,
            days,
            if days == 1 { "" } else { "s" }
        ),
        None => format!(
            "{} ({}) {} records, generated {} (date unparsable)",
            source.name, mode, source.count, date
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fixture matching the documented schema — stands in for the real
    /// `knowledge_meta.json` until the update pipeline generates it.
    const FIXTURE: &str = r#"{
        "sources": [
            {
                "name": "bioconda_tools",
                "description": "Bioconda CLI tool database",
                "data_file": "bioconda_tools.jsonl",
                "count": 6132,
                "generated_at": "2026-08-01T00:00:00Z",
                "auto": true
            },
            {
                "name": "skills_index",
                "data_file": "skills_index.jsonl",
                "count": 562,
                "generated_at": "2026-08-02T12:30:00Z",
                "auto": true
            },
            {
                "name": "manual_curation",
                "data_file": "manual.jsonl",
                "count": 3,
                "generated_at": "2025-01-01T00:00:00Z",
                "auto": false
            }
        ]
    }"#;

    fn fixed_now() -> chrono::DateTime<chrono::Utc> {
        chrono::DateTime::parse_from_rfc3339("2026-08-22T00:00:00Z")
            .unwrap()
            .with_timezone(&chrono::Utc)
    }

    #[test]
    fn parse_accepts_documented_schema() {
        let meta = KnowledgeMeta::parse(FIXTURE).expect("fixture must parse");
        assert_eq!(meta.sources.len(), 3);
        assert_eq!(meta.source("bioconda_tools").unwrap().count, 6132);
    }

    #[test]
    fn parse_rejects_malformed_json() {
        assert!(KnowledgeMeta::parse("{not json").is_err());
        assert!(
            KnowledgeMeta::parse("[]").is_err(),
            "root must be an object"
        );
        assert!(KnowledgeMeta::parse("{}").is_ok(), "empty sources allowed");
    }

    #[test]
    fn parse_defaults_missing_description() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let skills = meta.source("skills_index").unwrap();
        assert_eq!(skills.description, "");
        assert_eq!(skills.count, 562);
    }

    #[test]
    fn staleness_days_computed_from_generated_at() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let now = fixed_now();
        // 2026-08-01 -> 2026-08-22 = 21 whole days
        assert_eq!(
            meta.source("bioconda_tools").unwrap().staleness_days(now),
            Some(21)
        );
        // 2026-08-02 12:30 -> 2026-08-22 00:00 = 19 whole days
        assert_eq!(
            meta.source("skills_index").unwrap().staleness_days(now),
            Some(19)
        );
    }

    #[test]
    fn future_generated_at_never_stale() {
        let now = fixed_now();
        let future = KnowledgeSource {
            name: "future".into(),
            description: String::new(),
            data_file: "future.jsonl".into(),
            count: 1,
            generated_at: "2026-08-30T00:00:00Z".into(),
            auto: true,
        };
        assert_eq!(future.staleness_days(now), Some(0));
        assert!(!future.is_stale(now));
    }

    #[test]
    fn stale_threshold_excludes_manual_sources() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let now = fixed_now();
        // 2025-01-01 is far beyond 60 days, but auto=false exempts it.
        assert!(!meta.source("manual_curation").unwrap().is_stale(now));
        assert_eq!(
            meta.source("manual_curation").unwrap().staleness_days(now),
            Some(598)
        );
    }

    #[test]
    fn stale_boundary_is_exclusive() {
        let now = fixed_now();
        let boundary = KnowledgeSource {
            name: "boundary".into(),
            description: String::new(),
            data_file: "boundary.jsonl".into(),
            count: 1,
            generated_at: "2026-06-23T00:00:00Z".into(), // 60 days before the fixed now (08-22)
            auto: true,
        };
        assert_eq!(boundary.staleness_days(now), Some(60));
        assert!(
            !boundary.is_stale(now),
            "60 days is not stale (exclusive boundary)"
        );

        let mut over = boundary.clone();
        over.generated_at = "2026-06-22T00:00:00Z".into(); // 61 days before
        assert_eq!(over.staleness_days(now), Some(61));
        assert!(over.is_stale(now), "61 days is stale");
    }

    #[test]
    fn parse_accepts_sources_as_named_object() {
        let json = r#"{
            "sources": {
                "bioconda_tools": {
                    "data_file": "bioconda_tools.jsonl",
                    "count": 6132,
                    "generated_at": "2026-08-01T00:00:00Z",
                    "auto": true
                }
            }
        }"#;
        let meta = KnowledgeMeta::parse(json).expect("named-object sources must parse");
        let src = meta.source("bioconda_tools").expect("source present");
        assert_eq!(src.count, 6132);
        assert_eq!(src.data_file, "bioconda_tools.jsonl");
    }

    #[test]
    fn parse_accepts_bare_object_of_sources() {
        let json = r#"{
            "bioconda_tools": {
                "data_file": "bioconda_tools.jsonl",
                "count": 6132,
                "generated_at": "2026-08-01T00:00:00Z",
                "auto": true
            }
        }"#;
        let meta = KnowledgeMeta::parse(json).expect("bare object must parse");
        let src = meta.source("bioconda_tools").expect("source present");
        assert_eq!(src.count, 6132);
        assert!(src.auto);
    }

    #[test]
    fn parse_rejects_non_object_shapes() {
        assert!(
            KnowledgeMeta::parse("[]").is_err(),
            "root must be an object"
        );
        assert!(
            KnowledgeMeta::parse(r#"{"sources": 42}"#).is_err(),
            "sources must be an object or array"
        );
    }

    #[test]
    fn generated_date_renders_yyyy_mm_dd() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        assert_eq!(
            meta.source("bioconda_tools")
                .unwrap()
                .generated_date()
                .as_deref(),
            Some("2026-08-01")
        );
    }

    #[test]
    fn freshness_line_contains_date_and_count() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let line = freshness_line(meta.source("bioconda_tools").unwrap(), fixed_now());
        assert!(line.contains("2026-08-01"), "{line}");
        assert!(line.contains("6132 records"), "{line}");
        assert!(line.contains("21 days ago"), "{line}");
    }

    #[test]
    fn freshness_line_singular_day() {
        let now = fixed_now();
        let src = KnowledgeSource {
            name: "daily".into(),
            description: String::new(),
            data_file: "daily.jsonl".into(),
            count: 1,
            generated_at: "2026-08-21T00:00:00Z".into(),
            auto: true,
        };
        assert!(freshness_line(&src, now).contains("1 day ago"));
    }

    #[test]
    fn freshness_line_for_by_name() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let line = freshness_line_for(&meta, "bioconda_tools", fixed_now());
        assert!(line.unwrap().contains("bioconda_tools"));
        assert!(freshness_line_for(&meta, "nope", fixed_now()).is_none());
    }

    #[test]
    fn format_source_row_shows_mode() {
        let meta = KnowledgeMeta::parse(FIXTURE).unwrap();
        let row = format_source_row(meta.source("bioconda_tools").unwrap(), fixed_now());
        assert!(row.contains("(auto)"), "{row}");
        assert!(row.contains("6132 records"), "{row}");
        let manual = format_source_row(meta.source("manual_curation").unwrap(), fixed_now());
        assert!(manual.contains("(manual)"), "{manual}");
    }
}
