//! Container build and packaging utilities.
//!
//! Provides functionality to package oxo-flow workflows into self-contained
//! container images (Docker/Singularity) for portable execution.

use crate::config::WorkflowConfig;
use crate::error::Result;

/// Container format to generate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContainerFormat {
    /// Dockerfile for Docker/Podman builds.
    Docker,
    /// Singularity definition file.
    Singularity,
}

impl std::fmt::Display for ContainerFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Docker => write!(f, "docker"),
            Self::Singularity => write!(f, "singularity"),
        }
    }
}

/// Configuration for container packaging.
#[derive(Debug, Clone)]
pub struct PackageConfig {
    /// Container format to generate.
    pub format: ContainerFormat,

    /// Base image to use.
    pub base_image: String,

    /// Whether to include reference data.
    pub include_data: bool,

    /// Additional labels/metadata.
    pub labels: Vec<(String, String)>,
}

impl Default for PackageConfig {
    fn default() -> Self {
        Self {
            format: ContainerFormat::Docker,
            base_image: "ubuntu:22.04".to_string(),
            include_data: false,
            labels: Vec::new(),
        }
    }
}

/// Generate a Dockerfile from a workflow configuration.
pub fn generate_dockerfile(workflow: &WorkflowConfig, config: &PackageConfig) -> Result<String> {
    let mut dockerfile = String::new();

    // Header
    dockerfile.push_str(&format!(
        "# Auto-generated by oxo-flow for workflow: {}\n",
        workflow.workflow.name
    ));
    dockerfile.push_str(&format!("FROM {}\n\n", config.base_image));

    // Labels
    dockerfile.push_str(&format!(
        "LABEL org.opencontainers.image.title=\"{}\"\n",
        workflow.workflow.name
    ));
    dockerfile.push_str(&format!(
        "LABEL org.opencontainers.image.version=\"{}\"\n",
        workflow.workflow.version
    ));
    for (key, value) in &config.labels {
        dockerfile.push_str(&format!("LABEL {key}=\"{value}\"\n"));
    }
    dockerfile.push('\n');

    // Install system dependencies
    dockerfile.push_str("# System dependencies\n");
    dockerfile.push_str("RUN apt-get update && apt-get install -y \\\n");
    dockerfile.push_str("    curl wget git build-essential \\\n");
    dockerfile.push_str("    && rm -rf /var/lib/apt/lists/*\n\n");

    // Collect unique environment types needed
    let mut needs_conda = false;
    let mut docker_images = Vec::new();

    for rule in &workflow.rules {
        if rule.environment.conda.is_some() || rule.environment.pixi.is_some() {
            needs_conda = true;
        }
        if let Some(ref img) = rule.environment.docker {
            if !docker_images.contains(img) {
                docker_images.push(img.clone());
            }
        }
    }

    // Install conda if needed
    if needs_conda {
        dockerfile.push_str("# Install Miniforge (conda)\n");
        dockerfile.push_str("RUN curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh \\\n");
        dockerfile.push_str("    && bash Miniforge3-Linux-x86_64.sh -b -p /opt/conda \\\n");
        dockerfile.push_str("    && rm Miniforge3-Linux-x86_64.sh\n");
        dockerfile.push_str("ENV PATH=/opt/conda/bin:$PATH\n\n");

        // Create conda environments
        for rule in &workflow.rules {
            if let Some(ref conda_env) = rule.environment.conda {
                dockerfile.push_str(&format!("# Conda environment for rule: {}\n", rule.name));
                dockerfile.push_str(&format!("COPY {conda_env} /workflow/envs/\n"));
                let env_filename = std::path::Path::new(conda_env)
                    .file_name()
                    .map(|f| f.to_string_lossy().to_string())
                    .unwrap_or_else(|| conda_env.clone());
                dockerfile.push_str(&format!(
                    "RUN conda env create -f /workflow/envs/{env_filename} -n {}\n\n",
                    rule.name
                ));
            }
        }
    }

    // Copy workflow files
    dockerfile.push_str("# Copy workflow\n");
    dockerfile.push_str("WORKDIR /workflow\n");
    dockerfile.push_str("COPY . /workflow/\n\n");

    // Entry point
    dockerfile.push_str("# Default entrypoint\n");
    dockerfile.push_str("ENTRYPOINT [\"oxo-flow\", \"run\"]\n");

    Ok(dockerfile)
}

/// Generate a Singularity definition file from a workflow configuration.
pub fn generate_singularity_def(
    workflow: &WorkflowConfig,
    config: &PackageConfig,
) -> Result<String> {
    let mut def = String::new();

    def.push_str(&format!(
        "# Auto-generated by oxo-flow for workflow: {}\n",
        workflow.workflow.name
    ));
    def.push_str("Bootstrap: docker\n");
    def.push_str(&format!("From: {}\n\n", config.base_image));

    def.push_str("%labels\n");
    def.push_str(&format!(
        "    Author {}\n",
        workflow.workflow.author.as_deref().unwrap_or("oxo-flow")
    ));
    def.push_str(&format!("    Version {}\n", workflow.workflow.version));
    def.push_str(&format!(
        "    Description {}\n\n",
        workflow
            .workflow
            .description
            .as_deref()
            .unwrap_or("oxo-flow workflow")
    ));

    def.push_str("%post\n");
    def.push_str("    apt-get update && apt-get install -y curl wget git build-essential\n");
    def.push_str("    rm -rf /var/lib/apt/lists/*\n\n");

    def.push_str("%runscript\n");
    def.push_str("    exec oxo-flow run \"$@\"\n");

    Ok(def)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_basic_dockerfile() {
        let workflow = WorkflowConfig::parse(
            r#"
            [workflow]
            name = "test"
            version = "1.0.0"
        "#,
        )
        .unwrap();

        let config = PackageConfig::default();
        let dockerfile = generate_dockerfile(&workflow, &config).unwrap();
        assert!(dockerfile.contains("FROM ubuntu:22.04"));
        assert!(dockerfile.contains("test"));
    }

    #[test]
    fn generate_dockerfile_with_conda() {
        let workflow = WorkflowConfig::parse(
            r#"
            [workflow]
            name = "conda-test"
            version = "1.0.0"

            [[rules]]
            name = "step1"
            output = ["out.txt"]
            shell = "echo hello"

            [rules.environment]
            conda = "envs/tools.yaml"
        "#,
        )
        .unwrap();

        let config = PackageConfig::default();
        let dockerfile = generate_dockerfile(&workflow, &config).unwrap();
        assert!(dockerfile.contains("Miniforge"));
        assert!(dockerfile.contains("conda env create"));
    }

    #[test]
    fn generate_singularity_def_basic() {
        let workflow = WorkflowConfig::parse(
            r#"
            [workflow]
            name = "sing-test"
            version = "1.0.0"
        "#,
        )
        .unwrap();

        let config = PackageConfig {
            format: ContainerFormat::Singularity,
            ..Default::default()
        };
        let def = generate_singularity_def(&workflow, &config).unwrap();
        assert!(def.contains("Bootstrap: docker"));
        assert!(def.contains("From: ubuntu:22.04"));
    }

    #[test]
    fn container_format_display() {
        assert_eq!(ContainerFormat::Docker.to_string(), "docker");
        assert_eq!(ContainerFormat::Singularity.to_string(), "singularity");
    }
}
