//! SPA asset-consistency gate (audit finding F1, CRITICAL).
//!
//! `static/index.html` is committed to git while the bundle it references is
//! not (`static/assets/*` is gitignored — it is regenerated by
//! `npm run build` in `frontend/`). The two can therefore drift apart: a
//! committed index.html whose hashed filenames match nothing on disk serves a
//! blank page, because the browser gets a 404 (or the SPA fallback HTML) for
//! the entry `<script>` and React never mounts.
//!
//! This test is the gate: every `assets/…` filename named by index.html must
//! exist next to it. It reads the compile-time directory
//! (`CARGO_MANIFEST_DIR/static`) — the same source checkout `frontend_dir()`
//! falls back to — so it fails at build/test time instead of in a browser.
//!
//! When `static/assets/` is absent entirely the checkout simply has no
//! frontend build (the assets are gitignored and CI's `test` job does not run
//! npm); that is reported and skipped rather than failed. The moment ANY
//! asset exists, the whole set must agree with index.html.

use std::path::PathBuf;
use std::sync::OnceLock;

/// `assets/…` references in the served SPA index (src/href on script/link).
const ASSET_REF: &str = r#"(?:src|href)="\.?/?assets/([^"]+)""#;

fn static_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("static")
}

fn referenced_assets(index_html: &str) -> Vec<String> {
    static RE: OnceLock<regex::Regex> = OnceLock::new();
    let re = RE.get_or_init(|| regex::Regex::new(ASSET_REF).expect("asset reference regex"));
    re.captures_iter(index_html)
        .map(|c| c[1].to_string())
        .collect()
}

#[test]
fn spa_index_references_the_built_bundle() {
    let index_path = static_dir().join("index.html");
    let index_html = std::fs::read_to_string(&index_path).unwrap_or_else(|e| {
        panic!(
            "SPA index {} is unreadable ({e}) — it is tracked in git, so a \
             missing file means the checkout is broken",
            index_path.display()
        )
    });
    let refs = referenced_assets(&index_html);
    assert!(
        !refs.is_empty(),
        "static/index.html references no built assets — the SPA cannot load. \
         Run `npm run build` in frontend/."
    );
    assert!(
        refs.iter()
            .any(|a| a.starts_with("index-") && a.ends_with(".js")),
        "static/index.html references no `index-*.js` entry bundle: {refs:?}"
    );
}

#[test]
fn every_asset_referenced_by_spa_index_exists() {
    let dir = static_dir();
    let index_html = std::fs::read_to_string(dir.join("index.html")).expect("SPA index.html");
    let refs = referenced_assets(&index_html);
    assert!(
        !refs.is_empty(),
        "static/index.html references no built assets — run `npm run build` in frontend/."
    );

    let assets_dir = dir.join("assets");
    if !assets_dir.is_dir() {
        println!(
            "SKIP asset existence check: {} does not exist — this checkout has \
             no frontend build (assets are gitignored). Run `npm run build` in \
             frontend/ to enable the gate.",
            assets_dir.display()
        );
        return;
    }

    let missing: Vec<&String> = refs
        .iter()
        .filter(|name| !assets_dir.join(name.as_str()).is_file())
        .collect();
    assert!(
        missing.is_empty(),
        "static/index.html references assets that are missing from \
         static/assets/ (the SPA white-screens on them): {missing:?}. \
         index.html and the bundle come from different builds — run \
         `npm run build` in frontend/ to regenerate both together."
    );
}

/// The regex itself: a ref must be captured from both `src` and `href`, and
/// must not swallow surrounding markup.
#[test]
fn asset_reference_extraction_covers_script_and_link_tags() {
    let html = r#"<script type="module" crossorigin src="./assets/index-AbCdEf12.js"></script>
<link rel="modulepreload" crossorigin href="./assets/react-XyZ09876.js">
<link rel="stylesheet" crossorigin href="./assets/dag-QqRrStUv.css">
<link rel="icon" href="./favicon.svg">
<div src="not-an-asset"></div>"#;
    assert_eq!(
        referenced_assets(html),
        vec![
            "index-AbCdEf12.js".to_string(),
            "react-XyZ09876.js".to_string(),
            "dag-QqRrStUv.css".to_string(),
        ]
    );
}
