#!/bin/bash
# Auto-generated dependency-aware submit script
# Generated by oxo-flow

set -e

# Track job IDs
declare -A JOB_IDS

echo 'Submitting setup_environment...'
JOB_IDS[setup_environment]=$(sbatch dep-test/setup_environment.sh)
echo '  Submitted setup_environment as job ID: ${JOB_IDS[setup_environment]}'

echo 'Submitting run_alignment...'
JOB_IDS[run_alignment]=$(sbatch --dependency=afterok:${JOB_IDS[setup_environment]} dep-test/run_alignment.sh)
echo '  Submitted run_alignment as job ID: ${JOB_IDS[run_alignment]}'

echo 'Submitting gpu_variant_calling...'
JOB_IDS[gpu_variant_calling]=$(sbatch --dependency=afterok:${JOB_IDS[run_alignment]} dep-test/gpu_variant_calling.sh)
echo '  Submitted gpu_variant_calling as job ID: ${JOB_IDS[gpu_variant_calling]}'

echo 'Submitting deep_learning...'
JOB_IDS[deep_learning]=$(sbatch --dependency=afterok:${JOB_IDS[gpu_variant_calling]} dep-test/deep_learning.sh)
echo '  Submitted deep_learning as job ID: ${JOB_IDS[deep_learning]}'

echo 'Submitting run_qc...'
JOB_IDS[run_qc]=$(sbatch --dependency=afterok:${JOB_IDS[setup_environment]} dep-test/run_qc.sh)
echo '  Submitted run_qc as job ID: ${JOB_IDS[run_qc]}'

echo 'Submitting generate_report...'
JOB_IDS[generate_report]=$(sbatch --dependency=afterok:${JOB_IDS[deep_learning]}:${JOB_IDS[gpu_variant_calling]}:${JOB_IDS[run_alignment]}:${JOB_IDS[run_qc]} dep-test/generate_report.sh)
echo '  Submitted generate_report as job ID: ${JOB_IDS[generate_report]}'

echo 'All jobs submitted successfully!'
echo 'Job ID mapping:'
for name in "${!JOB_IDS[@]}"; do
  echo "  $name: ${JOB_IDS[$name]}"
done
